inherits = "dark_plus"

"ui.background" = {}

# "ui.statusline" = { bg = "none", fg = "gray" }
# "ui.statusline.inactive" = { bg = "none", fg = "dark-gray" }
#
# "ui.statusline.normal" = { fg = "gray", modifiers = ["bold"] }
# "ui.statusline.insert" = { fg = "blue" }
