lastupdatecheck: 0
recentrepos:
    - /home/fulmino/GDrive/env/cli
    - /home/fulmino/.local/share/Trash/files/nvim-treesitter.7
    - /home/fulmino/.local/share/nvim/site/pack/core/opt/nvim-treesitter
startuppopupversion: 5
didshowhunkstaginghint: false
lastversion: 0.62.2
customcommandshistory:
    - q
hidecommandlog: false
githubPullRequests:
    /home/fulmino/.local/share/Trash/files/nvim-treesitter.7:
        - headRefName: main
          number: 8616
          title: 'fix(health): healthcheck always fails runtimepath check'
          state: CLOSED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8616
          headRepositoryOwner: schang412
        - headRefName: main
          number: 8604
          title: 'feat(nix): add `writeText`/`writeTextDir` injections'
          state: OPEN
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8604
          headRepositoryOwner: player131007
        - headRefName: main
          number: 8549
          title: 'fix(health): normalize both sides of runtimepath comparison'
          state: CLOSED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8549
          headRepositoryOwner: urtzienriquez
        - headRefName: main
          number: 8541
          title: 'feat(ecmascript): add gql function highlighting for ecmascript injection'
          state: MERGED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8541
          headRepositoryOwner: ethanrutt
        - headRefName: main
          number: 8526
          title: 'fix(c_sharp): missing highlight for lambda modifier'
          state: MERGED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8526
          headRepositoryOwner: Ark1409
    /home/fulmino/.local/share/nvim/site/pack/core/opt/nvim-treesitter:
        - headRefName: main
          number: 8616
          title: 'fix(health): healthcheck always fails runtimepath check'
          state: CLOSED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8616
          headRepositoryOwner: schang412
        - headRefName: main
          number: 8604
          title: 'feat(nix): add `writeText`/`writeTextDir` injections'
          state: OPEN
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8604
          headRepositoryOwner: player131007
        - headRefName: main
          number: 8549
          title: 'fix(health): normalize both sides of runtimepath comparison'
          state: CLOSED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8549
          headRepositoryOwner: urtzienriquez
        - headRefName: main
          number: 8541
          title: 'feat(ecmascript): add gql function highlighting for ecmascript injection'
          state: MERGED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8541
          headRepositoryOwner: ethanrutt
        - headRefName: main
          number: 8526
          title: 'fix(c_sharp): missing highlight for lambda modifier'
          state: MERGED
          url: https://github.com/nvim-treesitter/nvim-treesitter/pull/8526
          headRepositoryOwner: Ark1409
    /home/fulmino/GDrive/env/cli: []
